version: "3.7"

services:

  siga-demo-application:
    image: siga-demo-application:latest
    ports:
      - "8444:8444"
    networks:
      siga:
        aliases:
          - siga-demo.localhost
    depends_on:
      - siga-webapp

  siga-webapp:
    build: siga-webapp
    ports:
      - "8443:8443"
    networks:
      siga:
        aliases:
          - siga.docker.internal
    volumes:
      - "siga-logs:/usr/local/tomcat/logs"
    depends_on:
      - ignite

  ignite:
    build:
      context: docker/docker-ignite/
    ports:
      - "47500:47500"
    networks:
      siga:
        aliases:
          - ignite.docker.internal
networks:
  siga:
    driver: bridge

volumes:
  siga-logs:
    name: siga-logs